export const activeCountry = () => [
  'Missouri',
  'Connecticut',
  'Vermont',
  'Washington',
  'Idaho',
  'North Dakota',
  'Wyoming',
  'Mississippi',
  'Delaware',
  'Alaska',
  'New Mexico',
  'Maine',
  'South Dakota',
  'Utah',
  'Louisiana',
  'Rhode Island',
  'Nebraska',
  'Iowa',
  'Oregon',
  'West Virginia',
];
