export const activeCountry = () => [
  'Connecticut',
  'Vermont',
  'Washington',
  'Idaho',
  'North Dakota',
  'Wyoming',
  'West Virginia',
  'Maine',
  'South Dakota',
  'Missouri',
  'Alaska',
  'New Mexico',
  'Delaware',
  'Utah',
  'Hawaii',
  'Oregon',
  'Mississippi',
  'Rhode Island',
  'Nebraska',
  'Iowa',
  'Louisiana',
  'Minnesota',
  'Massachusetts',
  'Colorado',
  'Maryland',
  'Oklahoma',
  'New Hampshire',
  'Nevada',
  'Georgia',
  'Kansas',
  'Wisconsin',
  'Arizona',
  'Texas',
  'Indiana',
  'Montana',
  'California',
  'Pennsylvania',
  'Arkansas',
  'Ohio',
  'New York',
  'Tennessee',
  'Michigan',
  'Florida',
  'New Jersey',
  'Illinois',
  'North Carolina',
  'Virginia',
  'Kentucky',
  'Alabama',
  'South Carolina',
];
